### ISSUE TITLE
bug: Sphinx not compiling on the worker 

### ISSUE THREAD

**Issue by pesap** [NREL/infrasys#18]
It looks like the runner fails to publish the documentation on the sphinx-build step. See related.

Related:
- https://github.com/NREL/infrasys/actions/runs/8726067749/job/23940468916

**Comment by pesap** [comment]
It looks like it is a sphinx problem: 

- https://github.com/sphinx-doc/sphinx/issues/12295#issuecomment-2060772469

**Comment by daniel-thom** [comment]
@pesap This seems fixed. Want to close?
